#datasources
spring:
  datasource:
    url: jdbc:mysql://localhost/db_manager?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
    username: root
    password: 123123

#jpa
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update

